# Site settings
name: Bioinformatics blog
email: aiqbal@age.mpg.de
url: https://aiqbal94.github.io
description: Some useful notes and templates.
author: Ayesha Iqbal
title: "BlogFolio"
permalink: pretty
baseurl: /jekyll-theme-blogfolio

# social
github:
  username: AIqbal94

linkedin:
  username: ayesha-iqbal-2726b6151
