# Site settings
name: Ayesha Iqbal
email: aiqbal@age.mpg.de
url: https://aiqbal94.github.io
description: Some useful notes and templates.
author: Ayesha Iqbal
title: "Bioinformatics Blog"
permalink: pretty
baseurl: 

# social
github:
  username: AIqbal94

linkedin:
  username: ayesha-iqbal-2726b6151
